name: Publish Packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack SMS.Net
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/SMS.Net/SMS.Net.csproj -o .
      - name: Pack SMS.Net.RavenSMS
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/SmsDeliveryChannels/SMS.Net.RavenSMS/SMS.Net.RavenSMS.csproj -o .
      - name: Pack SMS.Net.Avochato
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/SmsDeliveryChannels/SMS.Net.Avochato/SMS.Net.Avochato.csproj -o .
      - name: Pack SMS.Net.MessageBird
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/SmsDeliveryChannels/SMS.Net.MessageBird/SMS.Net.MessageBird.csproj -o .
      - name: Pack SMS.Net.Twilio
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/SmsDeliveryChannels/SMS.Net.Twilio/SMS.Net.Twilio.csproj -o .

      - name: Pack SMS.Net.DependencyInjection
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/DependencyInjection/SMS.Net.DependencyInjection/SMS.Net.DependencyInjection.csproj -o .
      - name: Pack SMS.Net.Avochato.DependencyInjection
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/DependencyInjection/SMS.Net.Avochato.DependencyInjection/SMS.Net.Avochato.DependencyInjection.csproj -o .
      - name: Pack SMS.Net.MessageBird.DependencyInjection
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/DependencyInjection/SMS.Net.MessageBird.DependencyInjection/SMS.Net.MessageBird.DependencyInjection.csproj -o .
      - name: Pack SMS.Net.Twilio.DependencyInjection
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/DependencyInjection/SMS.Net.Twilio.DependencyInjection/SMS.Net.Twilio.DependencyInjection.csproj -o .

      - name: Push packages
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Upload assets to release
        run: |
          chmod +x ./publish-assets.sh
          ./publish-assets.sh ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
