name: Build and Test

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SMS_NET_AVOCHATO_FROM_PHONE_NUMBER: ${{secrets.SMS_NET_AVOCHATO_FROM_PHONE_NUMBER}}
      SMS_NET_AVOCHATO_AUTHSECRET: ${{secrets.SMS_NET_AVOCHATO_AUTHSECRET}}
      SMS_NET_AVOCHATO_AUTHID: ${{secrets.SMS_NET_AVOCHATO_AUTHID}}
      SMS_NET_MESSAGEBIRD_FROM_PHONE_NUMBER: ${{secrets.SMS_NET_MESSAGEBIRD_FROM_PHONE_NUMBER}}
      SMS_NET_MESSAGEBIRD_ACCESSKEY: ${{secrets.SMS_NET_MESSAGEBIRD_ACCESSKEY}}
      SMS_NET_TWILIO_FROM_PHONE_NUMBER: ${{secrets.SMS_NET_TWILIO_FROM_PHONE_NUMBER}}
      SMS_NET_TWILIO_USERNAME: ${{secrets.SMS_NET_TWILIO_USERNAME}}
      SMS_NET_TWILIO_PASSWORD: ${{secrets.SMS_NET_TWILIO_PASSWORD}}
      SMS_NET_TEST_TO_PHONE_NUMBER: ${{secrets.SMS_NET_TEST_TO_PHONE_NUMBER}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
